resource_group_name = "rg-githubactions-demo"
location            = "eastus"
vnet_name           = "vnet-demo"
vnet_address_space  = "10.0.0.0/16"
admin_username      = "azureadmin"
admin_password      = "MyP@ssword123!"
